# Generated by Django 6.0 on 2025-12-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.CharField(db_index=True, max_length=50, verbose_name='房屋唯一标识ID')),
                ('title', models.CharField(max_length=200, verbose_name='房屋标题')),
                ('district', models.CharField(db_index=True, max_length=50, verbose_name='行政区')),
                ('district_area', models.CharField(db_index=True, max_length=100, verbose_name='细分区域')),
                ('layout', models.CharField(db_index=True, max_length=50, verbose_name='户型')),
                ('area', models.FloatField(verbose_name='房屋面积（平方米）')),
                ('floor', models.CharField(max_length=50, verbose_name='楼层信息')),
                ('direction', models.CharField(db_index=True, max_length=20, verbose_name='房屋朝向')),
                ('deal_price', models.IntegerField(verbose_name='成交总价（万元）')),
                ('deal_unit_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='成交单价')),
                ('deal_date', models.DateField(db_index=True, verbose_name='成交日期')),
            ],
            options={
                'verbose_name': '房屋交易记录',
                'verbose_name_plural': '房屋交易记录',
                'db_table': 'house_deal',
                'ordering': ['-deal_date'],
                'indexes': [models.Index(fields=['district', 'layout'], name='house_deal_distric_16b15d_idx'), models.Index(fields=['district_area', 'deal_date'], name='house_deal_distric_2e6719_idx')],
            },
        ),
    ]
