# Generated by Django 6.0 on 2025-12-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housedeal',
            name='city',
            field=models.CharField(db_index=True, default='北京', max_length=50, verbose_name='城市'),
        ),
    ]
